ALTER TABLE sessions ADD COLUMN rtk_tokens_saved INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN rtk_compressions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sessions ADD COLUMN rtk_cache_hits INTEGER NOT NULL DEFAULT 0;
