/**
 * Theme schema — defines color tokens for UI themes.
 * Each theme provides both light and dark mode variants.
 * Sourced from real product design systems (VoltAgent/awesome-design-md).
 */

export interface ThemeColors {
  bgBase: string;
  bgCard: string;
  bgElevated: string;
  bgSidebar: string;
  bgHover: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  border: string;
  borderStrong: string;
  accent: string;
  success: string;
  danger: string;
  warning: string;
}

export interface ThemeDefinition {
  id: string;
  name: string;
  author?: string;
  light: ThemeColors;
  dark: ThemeColors;
}

/** Map theme colors to CSS custom properties */
export function themeToCssVars(colors: ThemeColors): Record<string, string> {
  return {
    "--color-bg-base": colors.bgBase,
    "--color-bg-card": colors.bgCard,
    "--color-bg-elevated": colors.bgElevated,
    "--color-bg-sidebar": colors.bgSidebar,
    "--color-bg-hover": colors.bgHover,
    "--color-text-primary": colors.textPrimary,
    "--color-text-secondary": colors.textSecondary,
    "--color-text-muted": colors.textMuted,
    "--color-border": colors.border,
    "--color-border-strong": colors.borderStrong,
    "--color-accent": colors.accent,
    "--color-success": colors.success,
    "--color-danger": colors.danger,
    "--color-warning": colors.warning,
  };
}

// ─── Built-in Themes ───────────────────────────────────────────────────────

export const BUILTIN_THEMES: ThemeDefinition[] = [
  // ── Default — Companion brand, warm cream + deep orange accent ──
  {
    id: "default",
    name: "Companion",
    light: {
      bgBase: "#f5f3ef",
      bgCard: "#ffffff",
      bgElevated: "#f0ede8",
      bgSidebar: "#fafaf8",
      bgHover: "#ede9e3",
      textPrimary: "#1f2d3d",
      textSecondary: "#4b5563",
      textMuted: "#9ca3af",
      border: "#e5e0d8",
      borderStrong: "#d0cac0",
      accent: "#ff5722",
      success: "#34a853",
      danger: "#ea4335",
      warning: "#fbbc04",
    },
    dark: {
      bgBase: "#0a0a0a",
      bgCard: "#111111",
      bgElevated: "#1a1a1a",
      bgSidebar: "#0d0d0d",
      bgHover: "#1e1e1e",
      textPrimary: "#f0f0f0",
      textSecondary: "#aaaaaa",
      textMuted: "#707070",
      border: "#1e1e1e",
      borderStrong: "#2e2e2e",
      accent: "#ff5722",
      success: "#34a853",
      danger: "#ea4335",
      warning: "#fbbc04",
    },
  },

  // ── Linear — Developer project management ──
  {
    id: "linear",
    name: "Linear",
    author: "Linear Inc.",
    light: {
      bgBase: "#f7f8f8",
      bgCard: "#ffffff",
      bgElevated: "#f3f4f5",
      bgSidebar: "#f5f6f7",
      bgHover: "#edeef0",
      textPrimary: "#0f1011",
      textSecondary: "#4a4d52",
      textMuted: "#8a8f98",
      border: "#d0d6e0",
      borderStrong: "#b8bfc9",
      accent: "#5e6ad2",
      success: "#27a644",
      danger: "#d93036",
      warning: "#e0a020",
    },
    dark: {
      bgBase: "#08090a",
      bgCard: "#0f1011",
      bgElevated: "#191a1b",
      bgSidebar: "#08090a",
      bgHover: "#28282c",
      textPrimary: "#f7f8f8",
      textSecondary: "#d0d6e0",
      textMuted: "#62666d",
      border: "#23252a",
      borderStrong: "#34343a",
      accent: "#5e6ad2",
      success: "#27a644",
      danger: "#e5484d",
      warning: "#e0af68",
    },
  },

  // ── Vercel — Minimal black & white, ship red accent ──
  {
    id: "vercel",
    name: "Vercel",
    author: "Vercel Inc.",
    light: {
      bgBase: "#ffffff",
      bgCard: "#ffffff",
      bgElevated: "#fafafa",
      bgSidebar: "#fafafa",
      bgHover: "#f5f5f5",
      textPrimary: "#171717",
      textSecondary: "#4d4d4d",
      textMuted: "#808080",
      border: "#ebebeb",
      borderStrong: "#d4d4d4",
      accent: "#0070f3",
      success: "#0070f3",
      danger: "#ff5b4f",
      warning: "#f5a623",
    },
    dark: {
      bgBase: "#0a0a0a",
      bgCard: "#111111",
      bgElevated: "#1a1a1a",
      bgSidebar: "#0a0a0a",
      bgHover: "#1f1f1f",
      textPrimary: "#ededed",
      textSecondary: "#a1a1a1",
      textMuted: "#666666",
      border: "#252525",
      borderStrong: "#333333",
      accent: "#0070f3",
      success: "#0070f3",
      danger: "#ff5b4f",
      warning: "#f5a623",
    },
  },

  // ── Cursor — AI code editor, warm off-white + orange ──
  {
    id: "cursor",
    name: "Cursor",
    author: "Anysphere Inc.",
    light: {
      bgBase: "#f2f1ed",
      bgCard: "#f7f7f4",
      bgElevated: "#ebeae5",
      bgSidebar: "#f2f1ed",
      bgHover: "#e6e5e0",
      textPrimary: "#26251e",
      textSecondary: "#5c5b54",
      textMuted: "#8a8980",
      border: "#dddcd7",
      borderStrong: "#c8c7c2",
      accent: "#f54e00",
      success: "#1f8a65",
      danger: "#cf2d56",
      warning: "#c08532",
    },
    dark: {
      bgBase: "#1a1918",
      bgCard: "#222120",
      bgElevated: "#2a2928",
      bgSidebar: "#151413",
      bgHover: "#333231",
      textPrimary: "#e8e7e2",
      textSecondary: "#a5a49f",
      textMuted: "#6e6d68",
      border: "#333231",
      borderStrong: "#444342",
      accent: "#f54e00",
      success: "#3db982",
      danger: "#e85570",
      warning: "#d4993e",
    },
  },

  // ── Stripe — Financial SaaS, purple brand ──
  {
    id: "stripe",
    name: "Stripe",
    author: "Stripe Inc.",
    light: {
      bgBase: "#ffffff",
      bgCard: "#ffffff",
      bgElevated: "#f6f9fc",
      bgSidebar: "#f6f9fc",
      bgHover: "#edf2f7",
      textPrimary: "#061b31",
      textSecondary: "#273951",
      textMuted: "#64748d",
      border: "#e5edf5",
      borderStrong: "#cdd6e0",
      accent: "#533afd",
      success: "#15be53",
      danger: "#ea2261",
      warning: "#9b6829",
    },
    dark: {
      bgBase: "#0d1117",
      bgCard: "#141a22",
      bgElevated: "#1c2430",
      bgSidebar: "#0a0e14",
      bgHover: "#243040",
      textPrimary: "#f0f4f8",
      textSecondary: "#b0bec5",
      textMuted: "#607080",
      border: "#1e2a38",
      borderStrong: "#2c3a4a",
      accent: "#665efd",
      success: "#15be53",
      danger: "#ea2261",
      warning: "#d4a545",
    },
  },

  // ── Raycast — Productivity launcher, dark-native ──
  {
    id: "raycast",
    name: "Raycast",
    author: "Raycast GmbH",
    light: {
      bgBase: "#f8f8f8",
      bgCard: "#ffffff",
      bgElevated: "#f0f0f0",
      bgSidebar: "#f4f4f4",
      bgHover: "#eaeaea",
      textPrimary: "#1a1a1a",
      textSecondary: "#4d4d4d",
      textMuted: "#9c9c9d",
      border: "#e0e0e0",
      borderStrong: "#cccccc",
      accent: "#ff6363",
      success: "#5fc992",
      danger: "#ff6363",
      warning: "#ffbc33",
    },
    dark: {
      bgBase: "#07080a",
      bgCard: "#101111",
      bgElevated: "#1b1c1e",
      bgSidebar: "#07080a",
      bgHover: "#252829",
      textPrimary: "#f9f9f9",
      textSecondary: "#cecece",
      textMuted: "#6a6b6c",
      border: "#252829",
      borderStrong: "#2f3031",
      accent: "#ff6363",
      success: "#5fc992",
      danger: "#ff6363",
      warning: "#ffbc33",
    },
  },

  // ── Claude — Warm terracotta, parchment ──
  {
    id: "claude",
    name: "Claude",
    author: "Anthropic",
    light: {
      bgBase: "#f5f4ed",
      bgCard: "#faf9f5",
      bgElevated: "#edecea",
      bgSidebar: "#f0efe8",
      bgHover: "#e8e6dc",
      textPrimary: "#141413",
      textSecondary: "#5e5d59",
      textMuted: "#87867f",
      border: "#e8e6dc",
      borderStrong: "#d1cfc5",
      accent: "#c96442",
      success: "#2e8b57",
      danger: "#b53333",
      warning: "#d4910a",
    },
    dark: {
      bgBase: "#141413",
      bgCard: "#1c1c1a",
      bgElevated: "#252523",
      bgSidebar: "#111110",
      bgHover: "#30302e",
      textPrimary: "#f5f4ed",
      textSecondary: "#b0aea5",
      textMuted: "#6e6d68",
      border: "#30302e",
      borderStrong: "#3d3d3a",
      accent: "#d97757",
      success: "#4caf6e",
      danger: "#cf4040",
      warning: "#e0a020",
    },
  },

  // ── Supabase — Developer platform, green accent ──
  {
    id: "supabase",
    name: "Supabase",
    author: "Supabase Inc.",
    light: {
      bgBase: "#f8f9fa",
      bgCard: "#ffffff",
      bgElevated: "#f1f3f5",
      bgSidebar: "#f4f5f6",
      bgHover: "#eceef0",
      textPrimary: "#171717",
      textSecondary: "#4d4d4d",
      textMuted: "#898989",
      border: "#e0e0e0",
      borderStrong: "#cccccc",
      accent: "#3ecf8e",
      success: "#3ecf8e",
      danger: "#ef4444",
      warning: "#f59e0b",
    },
    dark: {
      bgBase: "#0f0f0f",
      bgCard: "#171717",
      bgElevated: "#242424",
      bgSidebar: "#0f0f0f",
      bgHover: "#2e2e2e",
      textPrimary: "#fafafa",
      textSecondary: "#b4b4b4",
      textMuted: "#606060",
      border: "#2e2e2e",
      borderStrong: "#393939",
      accent: "#3ecf8e",
      success: "#3ecf8e",
      danger: "#ef4444",
      warning: "#f59e0b",
    },
  },

  // ── Spotify — Music streaming, green on dark ──
  {
    id: "spotify",
    name: "Spotify",
    author: "Spotify AB",
    light: {
      bgBase: "#f5f5f5",
      bgCard: "#ffffff",
      bgElevated: "#eeeeee",
      bgSidebar: "#f0f0f0",
      bgHover: "#e8e8e8",
      textPrimary: "#191414",
      textSecondary: "#535353",
      textMuted: "#b3b3b3",
      border: "#dcdcdc",
      borderStrong: "#c8c8c8",
      accent: "#1ed760",
      success: "#1ed760",
      danger: "#f3727f",
      warning: "#ffa42b",
    },
    dark: {
      bgBase: "#121212",
      bgCard: "#181818",
      bgElevated: "#252525",
      bgSidebar: "#0e0e0e",
      bgHover: "#2a2a2a",
      textPrimary: "#ffffff",
      textSecondary: "#b3b3b3",
      textMuted: "#6a6a6a",
      border: "#292929",
      borderStrong: "#3e3e3e",
      accent: "#1ed760",
      success: "#1ed760",
      danger: "#f3727f",
      warning: "#ffa42b",
    },
  },

  // ── Notion — Clean productivity, blue accent ──
  {
    id: "notion",
    name: "Notion",
    author: "Notion Labs",
    light: {
      bgBase: "#ffffff",
      bgCard: "#ffffff",
      bgElevated: "#f6f5f4",
      bgSidebar: "#f7f6f3",
      bgHover: "#eeeded",
      textPrimary: "#1a1a1a",
      textSecondary: "#615d59",
      textMuted: "#a39e98",
      border: "#e6e4e1",
      borderStrong: "#d4d1cc",
      accent: "#0075de",
      success: "#2a9d99",
      danger: "#e03e3e",
      warning: "#dd5b00",
    },
    dark: {
      bgBase: "#191919",
      bgCard: "#202020",
      bgElevated: "#2a2a2a",
      bgSidebar: "#151515",
      bgHover: "#333333",
      textPrimary: "#e8e8e8",
      textSecondary: "#9b9a97",
      textMuted: "#6b6966",
      border: "#2e2e2e",
      borderStrong: "#3e3e3e",
      accent: "#529cca",
      success: "#4dab9a",
      danger: "#e06060",
      warning: "#e88a30",
    },
  },

  // ── PostHog — Analytics platform, warm olive + orange ──
  {
    id: "posthog",
    name: "PostHog",
    author: "PostHog Inc.",
    light: {
      bgBase: "#fdfdf8",
      bgCard: "#ffffff",
      bgElevated: "#eeefe9",
      bgSidebar: "#f4f5ef",
      bgHover: "#e5e7e0",
      textPrimary: "#23251d",
      textSecondary: "#4d4f46",
      textMuted: "#9ea096",
      border: "#bfc1b7",
      borderStrong: "#a8aaa0",
      accent: "#f54e00",
      success: "#1f8a65",
      danger: "#dc2626",
      warning: "#f7a501",
    },
    dark: {
      bgBase: "#141511",
      bgCard: "#1c1d18",
      bgElevated: "#262720",
      bgSidebar: "#101109",
      bgHover: "#30312a",
      textPrimary: "#eaebe5",
      textSecondary: "#a8aaa0",
      textMuted: "#6a6c62",
      border: "#2e2f28",
      borderStrong: "#3e3f38",
      accent: "#f54e00",
      success: "#3db982",
      danger: "#ef4444",
      warning: "#f7a501",
    },
  },
];
