/**
 * Theme schema — defines color tokens for UI themes.
 * Each theme provides both light and dark mode variants.
 */

export interface ThemeColors {
  bgBase: string;
  bgCard: string;
  bgElevated: string;
  bgSidebar: string;
  bgHover: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  border: string;
  borderStrong: string;
  accent: string;
  success: string;
  danger: string;
  warning: string;
}

export interface ThemeDefinition {
  id: string;
  name: string;
  author?: string;
  light: ThemeColors;
  dark: ThemeColors;
}

/** Map theme colors to CSS custom properties */
export function themeToCssVars(colors: ThemeColors): Record<string, string> {
  return {
    "--color-bg-base": colors.bgBase,
    "--color-bg-card": colors.bgCard,
    "--color-bg-elevated": colors.bgElevated,
    "--color-bg-sidebar": colors.bgSidebar,
    "--color-bg-hover": colors.bgHover,
    "--color-text-primary": colors.textPrimary,
    "--color-text-secondary": colors.textSecondary,
    "--color-text-muted": colors.textMuted,
    "--color-border": colors.border,
    "--color-border-strong": colors.borderStrong,
    "--color-accent": colors.accent,
    "--color-success": colors.success,
    "--color-danger": colors.danger,
    "--color-warning": colors.warning,
  };
}

// ─── Built-in Themes ───────────────────────────────────────────────────────

export const BUILTIN_THEMES: ThemeDefinition[] = [
  {
    id: "default",
    name: "Default",
    light: {
      bgBase: "#f5f3ef",
      bgCard: "#ffffff",
      bgElevated: "#f0ede8",
      bgSidebar: "#fafaf8",
      bgHover: "#ede9e3",
      textPrimary: "#1f2d3d",
      textSecondary: "#4b5563",
      textMuted: "#9ca3af",
      border: "#e5e0d8",
      borderStrong: "#d0cac0",
      accent: "#4285f4",
      success: "#34a853",
      danger: "#ea4335",
      warning: "#fbbc04",
    },
    dark: {
      bgBase: "#050505",
      bgCard: "#0d0d0d",
      bgElevated: "#161616",
      bgSidebar: "#0a0a0a",
      bgHover: "#1e1e1e",
      textPrimary: "#f0f0f0",
      textSecondary: "#aaaaaa",
      textMuted: "#808080",
      border: "#1e1e1e",
      borderStrong: "#2e2e2e",
      accent: "#4285f4",
      success: "#34a853",
      danger: "#ea4335",
      warning: "#fbbc04",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    author: "Wimer Hazenberg",
    light: {
      bgBase: "#fafafa",
      bgCard: "#ffffff",
      bgElevated: "#f0f0f0",
      bgSidebar: "#f5f5f5",
      bgHover: "#e8e8e8",
      textPrimary: "#272822",
      textSecondary: "#49483e",
      textMuted: "#90908a",
      border: "#e0e0e0",
      borderStrong: "#cccccc",
      accent: "#a6e22e",
      success: "#a6e22e",
      danger: "#f92672",
      warning: "#e6db74",
    },
    dark: {
      bgBase: "#272822",
      bgCard: "#2d2e27",
      bgElevated: "#3e3d32",
      bgSidebar: "#1e1f1c",
      bgHover: "#3e3d32",
      textPrimary: "#f8f8f2",
      textSecondary: "#cfcfc2",
      textMuted: "#75715e",
      border: "#3e3d32",
      borderStrong: "#49483e",
      accent: "#a6e22e",
      success: "#a6e22e",
      danger: "#f92672",
      warning: "#e6db74",
    },
  },
  {
    id: "nord",
    name: "Nord",
    author: "Arctic Ice Studio",
    light: {
      bgBase: "#eceff4",
      bgCard: "#ffffff",
      bgElevated: "#e5e9f0",
      bgSidebar: "#f0f2f6",
      bgHover: "#d8dee9",
      textPrimary: "#2e3440",
      textSecondary: "#3b4252",
      textMuted: "#7b88a1",
      border: "#d8dee9",
      borderStrong: "#c8ced9",
      accent: "#5e81ac",
      success: "#a3be8c",
      danger: "#bf616a",
      warning: "#ebcb8b",
    },
    dark: {
      bgBase: "#2e3440",
      bgCard: "#3b4252",
      bgElevated: "#434c5e",
      bgSidebar: "#272c36",
      bgHover: "#434c5e",
      textPrimary: "#eceff4",
      textSecondary: "#d8dee9",
      textMuted: "#7b88a1",
      border: "#3b4252",
      borderStrong: "#434c5e",
      accent: "#88c0d0",
      success: "#a3be8c",
      danger: "#bf616a",
      warning: "#ebcb8b",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    author: "Zeno Rocha",
    light: {
      bgBase: "#f8f8f2",
      bgCard: "#ffffff",
      bgElevated: "#f0f0e8",
      bgSidebar: "#f5f5ed",
      bgHover: "#e8e8e0",
      textPrimary: "#282a36",
      textSecondary: "#44475a",
      textMuted: "#9098a8",
      border: "#e0e0d8",
      borderStrong: "#cccccc",
      accent: "#bd93f9",
      success: "#50fa7b",
      danger: "#ff5555",
      warning: "#f1fa8c",
    },
    dark: {
      bgBase: "#282a36",
      bgCard: "#2d2f3d",
      bgElevated: "#383a4a",
      bgSidebar: "#21222c",
      bgHover: "#44475a",
      textPrimary: "#f8f8f2",
      textSecondary: "#cccee0",
      textMuted: "#6272a4",
      border: "#383a4a",
      borderStrong: "#44475a",
      accent: "#bd93f9",
      success: "#50fa7b",
      danger: "#ff5555",
      warning: "#f1fa8c",
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin",
    author: "Catppuccin",
    light: {
      bgBase: "#eff1f5",
      bgCard: "#ffffff",
      bgElevated: "#e6e9ef",
      bgSidebar: "#f2f4f8",
      bgHover: "#dce0e8",
      textPrimary: "#4c4f69",
      textSecondary: "#5c5f77",
      textMuted: "#9ca0b0",
      border: "#dce0e8",
      borderStrong: "#bcc0cc",
      accent: "#8839ef",
      success: "#40a02b",
      danger: "#d20f39",
      warning: "#df8e1d",
    },
    dark: {
      bgBase: "#1e1e2e",
      bgCard: "#252536",
      bgElevated: "#313244",
      bgSidebar: "#181825",
      bgHover: "#313244",
      textPrimary: "#cdd6f4",
      textSecondary: "#bac2de",
      textMuted: "#6c7086",
      border: "#313244",
      borderStrong: "#45475a",
      accent: "#cba6f7",
      success: "#a6e3a1",
      danger: "#f38ba8",
      warning: "#f9e2af",
    },
  },
  {
    id: "tokyonight",
    name: "Tokyo Night",
    author: "Folke Lemaitre",
    light: {
      bgBase: "#e1e2e7",
      bgCard: "#ffffff",
      bgElevated: "#d5d6db",
      bgSidebar: "#e9eaf0",
      bgHover: "#cccdd3",
      textPrimary: "#343b58",
      textSecondary: "#4c505e",
      textMuted: "#9099b0",
      border: "#d0d1d8",
      borderStrong: "#b8b9c0",
      accent: "#7aa2f7",
      success: "#9ece6a",
      danger: "#f7768e",
      warning: "#e0af68",
    },
    dark: {
      bgBase: "#1a1b26",
      bgCard: "#1f2031",
      bgElevated: "#292a3c",
      bgSidebar: "#16161e",
      bgHover: "#292a3c",
      textPrimary: "#c0caf5",
      textSecondary: "#a9b1d6",
      textMuted: "#565f89",
      border: "#292a3c",
      borderStrong: "#3b3d57",
      accent: "#7aa2f7",
      success: "#9ece6a",
      danger: "#f7768e",
      warning: "#e0af68",
    },
  },
  {
    id: "gruvbox",
    name: "Gruvbox",
    author: "Pavel Pertsev",
    light: {
      bgBase: "#fbf1c7",
      bgCard: "#ffffff",
      bgElevated: "#f2e5bc",
      bgSidebar: "#f7edcc",
      bgHover: "#ebdbb2",
      textPrimary: "#3c3836",
      textSecondary: "#504945",
      textMuted: "#928374",
      border: "#ebdbb2",
      borderStrong: "#d5c4a1",
      accent: "#458588",
      success: "#98971a",
      danger: "#cc241d",
      warning: "#d79921",
    },
    dark: {
      bgBase: "#282828",
      bgCard: "#2e2e2e",
      bgElevated: "#3c3836",
      bgSidebar: "#1d2021",
      bgHover: "#3c3836",
      textPrimary: "#ebdbb2",
      textSecondary: "#d5c4a1",
      textMuted: "#928374",
      border: "#3c3836",
      borderStrong: "#504945",
      accent: "#83a598",
      success: "#b8bb26",
      danger: "#fb4934",
      warning: "#fabd2f",
    },
  },
  {
    id: "rosepine",
    name: "Rosé Pine",
    author: "Rosé Pine",
    light: {
      bgBase: "#faf4ed",
      bgCard: "#ffffff",
      bgElevated: "#f2e9e1",
      bgSidebar: "#f7f0e8",
      bgHover: "#ede5d8",
      textPrimary: "#575279",
      textSecondary: "#6e6a86",
      textMuted: "#9893a5",
      border: "#ede5d8",
      borderStrong: "#dfdad9",
      accent: "#907aa9",
      success: "#56949f",
      danger: "#b4637a",
      warning: "#ea9d34",
    },
    dark: {
      bgBase: "#191724",
      bgCard: "#1f1d2e",
      bgElevated: "#26233a",
      bgSidebar: "#15131e",
      bgHover: "#26233a",
      textPrimary: "#e0def4",
      textSecondary: "#c4c0d9",
      textMuted: "#6e6a86",
      border: "#26233a",
      borderStrong: "#393552",
      accent: "#c4a7e7",
      success: "#9ccfd8",
      danger: "#eb6f92",
      warning: "#f6c177",
    },
  },
  {
    id: "solarized",
    name: "Solarized",
    author: "Ethan Schoonover",
    light: {
      bgBase: "#fdf6e3",
      bgCard: "#ffffff",
      bgElevated: "#eee8d5",
      bgSidebar: "#f8f2e0",
      bgHover: "#e8e1cc",
      textPrimary: "#657b83",
      textSecondary: "#586e75",
      textMuted: "#93a1a1",
      border: "#eee8d5",
      borderStrong: "#d6d0bb",
      accent: "#268bd2",
      success: "#859900",
      danger: "#dc322f",
      warning: "#b58900",
    },
    dark: {
      bgBase: "#002b36",
      bgCard: "#073642",
      bgElevated: "#0a3f4e",
      bgSidebar: "#001f29",
      bgHover: "#0a3f4e",
      textPrimary: "#839496",
      textSecondary: "#93a1a1",
      textMuted: "#586e75",
      border: "#073642",
      borderStrong: "#0a3f4e",
      accent: "#268bd2",
      success: "#859900",
      danger: "#dc322f",
      warning: "#b58900",
    },
  },
  {
    id: "github",
    name: "GitHub",
    author: "Primer",
    light: {
      bgBase: "#ffffff",
      bgCard: "#ffffff",
      bgElevated: "#f6f8fa",
      bgSidebar: "#f6f8fa",
      bgHover: "#eef1f5",
      textPrimary: "#1f2328",
      textSecondary: "#59636e",
      textMuted: "#8b949e",
      border: "#d1d9e0",
      borderStrong: "#b4bcc6",
      accent: "#0969da",
      success: "#1a7f37",
      danger: "#d1242f",
      warning: "#bf8700",
    },
    dark: {
      bgBase: "#0d1117",
      bgCard: "#161b22",
      bgElevated: "#1c2129",
      bgSidebar: "#0a0e14",
      bgHover: "#1c2129",
      textPrimary: "#e6edf3",
      textSecondary: "#c9d1d9",
      textMuted: "#8b949e",
      border: "#21262d",
      borderStrong: "#30363d",
      accent: "#58a6ff",
      success: "#3fb950",
      danger: "#f85149",
      warning: "#d29922",
    },
  },
];
